Add a screenshot of the webapp in the README
nhcarrigan/timezone-chart pull request #66
Opened 2021-02-27 11:26 UTC by sachinh19

Signed-off-by: sachinh19 <sachinhaldavanekar@gmail.com>

# Pull Request

I read the guidelines, the guidelines mentioned that I needed to request on the issue that I would like to work on this and I commented on it. I also read a comment there mentioning that the first comprehensive PR would be reviewed and merged, so I went ahead with creating this.

## Description:

Adds a screenshot of the web app's usage in the README file.

## Related Issue:

Closes #65

2021-02-27 14:53 UTC, adityaraute commented
Why not paste the image directly?

2021-02-27 15:46 UTC, nhcarrigan commented
> Why not paste the image directly?

That works if you're editing the file directly on GitHub, but doesn't work locally. I much prefer this approach, actually, as it means replacing the image can be done by modifying the image file directly.

2021-02-27 15:47 UTC, nhcarrigan requested changes

2021-02-27 15:47 UTC, nhcarrigan commented on README.md
> +
```suggestion
![A screenshot of the website, depicting a form with date-time inputs, a dropdown with timezone selection, and a submit button.](assets/sample.png)

```

We should add alt-text to the image for accessibility purposes.

2021-02-28 10:59 UTC, adityaraute submitted a review, later dismissed

2021-02-28 15:07 UTC, nhcarrigan approved these changes
Looks good to me. I've given this a rebase - will merge once the CI passes.

2021-02-28 15:37 UTC, merged

2021-02-28 15:38 UTC, nhcarrigan commented
Congrats on your first pull request (PR).

Thank you for your contribution to the page. We are happy to accept these changes and look forward to future contributions.